# Generated by Django 5.2.17 on 2026-10-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('CS', 'Computer Science'), ('DA', 'Data Analytics')], default='CS', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('CS', 'Computer Science'), ('DA', 'Data Analytics')], default='CS', max_length=2),
        ),
    ]
